export interface Breed {
  id: string,
  position: number,
  title: string,
  description_short: string,
  description: string,
  temperament: string,
  origin: string,
  life_span_from: number,
  life_span_to: number,
  adaptability: number,
  affection_level: number,
  child_friendly: number,
  grooming: number,
  intelligence: number,
  health_issues: number,
  social_needs: number,
  stranger_friendly: number,
  img: string,
  moreImages: string[];
}
